### PR TITLE
Trigger save events when an item is featured

### PR DESCRIPTION
**Pull request by phproberto**
Currently items trigger events when they are saved or published/unpublished but there are some cases where we need to connect logic when an item is featured/unfeatured. This makes it happen in a B/C way.

There are other changes I did:

### Avoid controller logic in model method.

Change K2ControllerItems::featured() logic to process request, add system messages and perform redirections.

A model should never access request parameters directly. This is something to be done in controllers to allow reusing model methods everywhere. Now if you want to use $itemsModel->featured() anywhere to feature X items you cannot really do it because it requires parameters from request. 

Same for system messages. You may want to feature events but notify users by email or even not notifying them for an internal process. Using this logic in the model forces system messages to be added.

Same for redirections. A model should never redirect anybody anywhere. It's part of the controllers' job.

### Register K2 namespace and start using it.

This PR registers `K2` namespace in `administrator/components/com_k2/lib/src`. I think you should really ship a library with K2 and register namespace there but I didn't want to deal with that now and make this pull request harder to merge.

### K2\Traits\HasEvents trait.

This creates a `K2\Traits\HasEvents` trait that allows to unify the way events are triggered in all the models. It can save you a lot of lines of code and make event handling easier to handle/test. Converts this:

```php
	JPluginHelper::importPlugin('finder');
	$dispatcher = JDispatcher::getInstance();

	$result = $dispatcher->trigger('onFinderAfterSave', array($row, $isNew));
```

into this: 

```php
	$result = $this->triggerEvent('onFinderAfterSave', [$row, $isNew], ['finder']);
```

Also let's say that the dispatcher class is changed in joomla. You only have 1 place to adjust.

That trait is injected in the base K2Model so it's available to be used in all the models. I haven't changed any model event to avoid blocking this PR but it should be easy to do and will allow you to remove a lot of code.

### CODE REVIEW

**Comment by phproberto** [comment]
By the way I ensured that all the changes here are compatible with old joomla versions + PHP5.4+

**Comment by fevangelou** [comment]
Working on some fancy K2 project Roberto? 😄 

Thanks for this. The featured event does make sense.

To be honest though, it's not PHP 5.4 support I want to maintain, but rather J1.5/2.5 support (it's a business decision for me, I'm not into S/M stuff). E.g. I'm pretty sure there is no registerNamespace() method in J1.5...

I will integrate the plugin events for when the featured state is toggled in the next upgrade of K2 for sure, but I will patch K2 earlier if you wanna test things out.

I do appreciate your time and effort but this is not the Joomla repo, so there is no need to do all this work beforehand. Simply request something and if it makes sense, I'm adding it in. Plain and simple.

For the record, I'm looking at moving completely away from Joomla's MVC in mid-2020 in order to support (as much as humanly possible) all Joomla versions from 1.5 up to 4.x and potentially other CMSs in the near future. This means that the entire app structure will change and actual app files will be combined under a single location with pointers in Joomla required locations.

**Comment by phproberto** [comment]
I cannot imagine anything worse than making a contributor feeling he wasted his time. You can request changes, submit your own patches... whatever except telling someone that took the time to contribute to your project that "plain and simply" he lost his time because you don't want contributors, you want issue reporters. 

I suggest you to add a HUGE note on the README explaining that code is not welcome and you only want people to use this to read the code and to report issues.

**Comment by phproberto** [comment]
wordpress

**Comment by fevangelou** [comment]
> I do appreciate your time and effort but this is not the Joomla repo, so there is no need to do all this work beforehand. Simply request something and if it makes sense, I'm adding it in. Plain and simple.

Additionally, the fact that you request something doesn't mean it should also get accepted as-is, or at all...

I was kind enough to say I will accept your request as a feature. Does the feature need to be line by line as you contributed it? Of course not.

Now, the fact that you're complaining about this, really speaks volumes... Too bad Roberto.

**Comment by phproberto** [comment]
You can reject it. You can even ask to implement something to support the ancient joomla 1.5. What you cannot say is "Your idea makes sense. I will implement it."

Don't try to change this to "I'm angry because you rejected my code". I'm not. I've contributed to a lot of opensource projects and I know when I'm wrong. 

I've invested my time checking your code, thinking how to improve the event system to easily call it in other actions like featured. I've implemented it and I've contributed it explaining all the benefits of my suggestion.

I hope your code improves the event system as much as mine did and allows you to remove the nightmare of triggers you have there. 

> I do appreciate your time and effort but this is not the Joomla repo, so there is no need to do all this work beforehand. Simply request something and if it makes sense, I'm adding it in. Plain and simple.

If you don't accept code ADD A BIG MESSAGE TELLING SO. Even WordPress does that right.

I won't lose more time telling you how to manage your project Fotis. Good luck.

**Comment by fevangelou** [comment]
Since you're pushing this, here goes:

> You can reject it. You can even ask to implement something to support the ancient joomla 1.5. What you cannot say is "Your idea makes sense. I will implement it."

Hold your horses there, cowboy. Surely your code is the greatest in the world. I won't steal it, you have my word.

> Don't try to change this to "I'm angry because you rejected my code". I'm not. I've contributed to a lot of opensource projects and I know when I'm wrong.

But you are. Sorry if I hurt your ego, but contributing some code to a project is one thing. "Running" a project is a whole different story.

> I've invested my time checking your code, thinking how to improve the event system to easily call it in other actions like featured. I've implemented it and I've contributed it explaining all the benefits of my suggestion. I hope your code improves the event system as much as mine did and allows you to remove the nightmare of triggers you have there.

Your contribution is a nice-to-have. But it doesn't make a dent to actual features or performance. And "improvement" as you say is purely speculation. Did you measure performance? Or by "improvement" you mean the 3 to 1 line change? It's just one way of doing things. It's not THE way. Get over it. Oh and these nightmares have worked for over a year. And they are part of your supposedly favorite CMS...

> If you don't accept code ADD A BIG MESSAGE TELLING SO. Even WordPress does that right.

I do accept code contributions, though surely I'm not Automattic. And I certainly don't like contributions from people with an attitude. I've never known you as a K2 developer or user either way. Jumping suddenly to contribute code means you somehow HAD to do this (probably a work requirement). And you're basically asking me to add a piece code to probably make YOUR life easier in the future. Why the f*** would anyone want to trigger plugin events when changing the "featured" flag. Hey, we might as well add it to all actions. What the hell...

> I won't lose more time telling you how to manage your project Fotis. Good luck.

But you ARE telling me what I should and shouldn't do. If you don't understand why I may need to support J1.5, then you're not thinking enough. And it's exactly this attitude that's pushed Joomla to shrink its CMS market share year over year. You're thinking as a developer and you probably write code for the sake of writing code. Not because it may get shit done for some people. And of course you're not thinking as a user.

Luck is for fools.

**Pull request closed without merging**
