### PR TITLE
Update files to allow the association of categories with multiple Extra ...

### PR DESCRIPTION
**Pull request by jameswadsworth**
We have added the possibility to:

1) associate an extra field with multiple extra fields groups. This avoids having to recreate and extra field for different extra fields group. i.e. you can reuse a header type in multiple extra field groups
2) associate a category with multiple extra field groups
3) associate a user group with multiple extra field groups

It means that extra fields can be used in many interesting ways for items and users.

### CODE REVIEW

**Comment by proweb** [comment]
Very, very need feature.
nice work @jameswadsworth 
could you make installation package with your version of K2 for testing?

**Comment by jameswadsworth** [comment]
Hi Proweb, I have been testing further and we have found a few bugs. I will commit the update files to the  repository next week and create an installation package for testing.

**Comment by proweb** [comment]
@jameswadsworth ok, waiting for you.
write me then you complete

**Comment by jameswadsworth** [comment]
Hi Proweb I have created a release for you to test 
https://github.com/jameswadsworth/k2/releases/tag/v0.1-alpha

**Pull request closed without merging**
